version: '3.7'

services:
  agent:
    image: gocd/gocd-agent-alpine-3.10:v19.7.0
    depends_on:
      - server
    environment:
      GO_SERVER_URL: http://server:8153/go
      AGENT_AUTO_REGISTER_KEY: 079e578b-87cc-46c9-9ab5-88997fc7ac59

  server:
    image: gocd/gocd-server:v19.7.0
    depends_on:
      - plugin-server
    environment:
      GOCD_PLUGIN_INSTALL_script-executor-task:
        https://github.com/gocd-contrib/script-executor-task/releases/download/0.3/script-executor-0.3.0.jar
      GOCD_PLUGIN_INSTALL_gocd-git-path-material-plugin:
        http://plugin-server/gocd-git-path-material-plugin-${VERSION}.jar
    ports:
      - 8153:8153
      - 8154:8154

  plugin-server:
    image: nginx
    volumes:
      - ./build/libs/:/usr/share/nginx/html:cached
    ports:
      - 80
