pipelines:
  action-movies:
    group: movies
    materials:
      action:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/TWChennai/gocd-git-path-sample.git
          path: action
          shallow_clone: true
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: ./run.sh action
  action-movies2:
    group: movies
    materials:
      action:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/TWChennai/gocd-git-path-sample.git
          path: action
    stages:
      - build:
          approval: manual
          jobs:
            build:
              tasks:
                - script: ./run.sh action
  animation-movies:
    group: movies
    materials:
      animation:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/TWChennai/gocd-git-path-sample.git
          path: animation
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: ./run.sh animation
  animation-and-action-movies:
    group: movies
    materials:
      animation-and-action:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/TWChennai/gocd-git-path-sample.git
          path: animation, action
          shallow_clone: true
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: ./run.sh animation
                - script: ./run.sh action
  both:
    group: movies
    materials:
      action:
        pipeline: action-movies
        stage: build
      action2:
        pipeline: action-movies2
        stage: build
      animation:
        pipeline: animation-movies
        stage: build
      animation-and-action-movies:
        pipeline: animation-and-action-movies
        stage: build
      integration:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/TWChennai/gocd-git-path-sample.git
          path: integration
          shallow_clone: true
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: echo "Run OK"
