pipelines:
  action-movies:
    group: movies
    materials:
      action:
        plugin_configuration:
          id: GitPathMaterial
        options:
          url: https://github.com/chadlwilson/gocd-git-path-sample.git
          path: action
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: ./run.sh action
  action-movies2:
    group: movies
    materials:
      action:
        plugin_configuration:
          id: GitPathMaterial
        options:
          url: https://github.com/chadlwilson/gocd-git-path-sample.git
          path: action
    stages:
      - build:
          approval: manual
          jobs:
            build:
              tasks:
                - script: ./run.sh action
  animation-movies:
    group: movies
    materials:
      animation:
        plugin_configuration:
          id: GitPathMaterial
        options:
          url: https://github.com/chadlwilson/gocd-git-path-sample.git
          path: animation
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: ./run.sh animation
  both:
    group: movies
    materials:
      action:
        pipeline: action-movies
        stage: build
      action2:
        pipeline: action-movies2
        stage: build
      animation:
        pipeline: animation-movies
        stage: build
      integration:
        plugin_configuration:
          id: GitPathMaterial
        options:
          url: https://github.com/chadlwilson/gocd-git-path-sample.git
          path: integration
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: echo "Run OK"
